### ISSUE TITLE
Uncaught TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by github-polymer-user** [HiroakiMikami/atom-translator-plus-dictionary#8]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.0-beta7
**System**: Unknown Windows Version
**Thrown From**: [translator-plus-dictionary](https://github.com/HiroakiMikami/atom-translator-plus-dictionary) package, v0.1.0

### Stack Trace

Uncaught TypeError: Cannot read property 'value' of undefined

```
At /C:/Users/user/.atom/packages/translator-plus-dictionary/lib/translator-plus-dictionary-view.coffee:189

TypeError: Cannot read property 'value' of undefined
    at TranslatorPlusDictionaryView.module.exports.TranslatorPlusDictionaryView.changed (file:///C:/Users/user/.atom/packages/translator-plus-dictionary/lib/translator-plus-dictionary-view.coffee:145:66)
    at TranslatorPlusDictionaryView.changed (file:///C:/Users/user/.atom/packages/translator-plus-dictionary/lib/translator-plus-dictionary-view.coffee:1:1)
    at file:///C:/Users/user/.atom/packages/translator-plus-dictionary/lib/translator-plus-dictionary-view.coffee:139:10
    at file:///C:/Users/user/.atom/packages/translator-plus-dictionary/lib/translator-plus-dictionary-view.coffee:75:34
    at initializeResultTemplte (file:///C:/Users/user/.atom/packages/translator-plus-dictionary/lib/translator-plus-dictionary-view.coffee:51:9)
    at file:///C:/Users/user/.atom/packages/translator-plus-dictionary/lib/translator-plus-dictionary-view.coffee:75:7
    at initilizeViewTempalte (file:///C:/Users/user/.atom/packages/translator-plus-dictionary/lib/translator-plus-dictionary-view.coffee:28:9)
    at Function.module.exports.TranslatorPlusDictionaryView.initializeTemplates (file:///C:/Users/user/.atom/packages/translator-plus-dictionary/lib/translator-plus-dictionary-view.coffee:73:5)
    at new TranslatorPlusDictionaryView (file:///C:/Users/user/.atom/packages/translator-plus-dictionary/lib/translator-plus-dictionary-view.coffee:96:34)
    at Object.module.exports.TranslatorPlusDictionary.translate (file:///C:/Users/user/.atom/packages/translator-plus-dictionary/lib/main.coffee:172:18)
    at atom-text-editor.subscriptions.add.atom.commands.add.translator-plus-dictionary:translate (file:///C:/Users/user/.atom/packages/translator-plus-dictionary/lib/main.coffee:106:106)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\user\AppData\Local\atom\app-1.6.0-beta7\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\user\AppData\Local\atom\app-1.6.0-beta7\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\user\AppData\Local\atom\app-1.6.0-beta7\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (C:\Users\user\AppData\Local\atom\app-1.6.0-beta7\resources\app.asar\src\atom-environment.js:1019:28)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.ipc.sendSync (C:\Users\user\AppData\Local\atom\app-1.6.0-beta7\resources\atom.asar\renderer\api\lib\ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\user\AppData\Local\atom\app-1.6.0-beta7\resources\atom.asar\renderer\api\lib\remote.js:143:29)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\user\AppData\Local\atom\app-1.6.0-beta7\resources\app.asar\src\context-menu-manager.js:172:33)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (C:\Users\user\AppData\Local\atom\app-1.6.0-beta7\resources\app.asar\src\window-event-handler.js:250:47)
    at HTMLDocument.<anonymous> (C:\Users\user\AppData\Local\atom\app-1.6.0-beta7\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -6:53.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -6:32.1.0 build:select-active-target (atom-text-editor.editor.is-focused)
     -6:29.7.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -6:29.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -6:27.3.0 command-palette:toggle (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
  2x -6:22.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -6:19.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -6:19.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -5:44.4.0 translator:translate (atom-text-editor.editor.is-focused)
     -5:27.9.0 core:move-down (button.btn)
     -4:42.5.0 translator:translate (atom-text-editor.editor.is-focused)
     -4:04.9.0 core:copy (atom-text-editor.editor.is-focused)
  3x -4:02.1.0 core:paste (atom-text-editor.editor.is-focused)
     -0:26.2.0 translator-plus-dictionary:translate (atom-text-editor.editor.is-focused)
  3x -0:16.2.0 core:backspace (atom-text-editor#translator-plus-dictionary.languages.editor.mini.is-focused)
     -0:03.1.0 translator-plus-dictionary:translate (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "polymer-atom"
    ],
    "packagesWithKeymapsDisabled": []
  },
  "translator-plus-dictionary": {
    "languages": "ru,fr",
    "microsoftTranslatorClientId": "atom",
    "microsoftTranslatorClientSecret": "4Z Snc3IPbC5strB3QdaiE57aUCscb2GOkVU/DyFJUs=",
    "primaryLanguage": "ru",
    "secondaryLanguage": "fr"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.26
atom-gmail-checker, v0.10.0
autoclose-html, v0.23.0
autocomplete-emojis, v2.2.2
autocomplete-google-suggest, v1.1.0
autocomplete-paths, v1.0.2
build, v0.55.0
build-grunt, v0.4.0
build-gulp, v0.7.0
build-make, v0.7.0
build-npm-apm, v0.8.0
color-picker, v2.1.1
file-icons, v1.6.17
google, v0.3.8
indent-guide-improved, v1.4.5
linter, v1.11.3
linter-csslint, v1.3.1
linter-jscs, v3.4.8
linter-jshint, v2.0.2
markdown-scroll-sync, v2.1.2
minimap, v4.19.0
minimap-bookmarks, v0.2.0
minimap-codeglance, v0.4.5
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.4.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-linter, v1.1.1
minimap-selection, v4.3.1
package-sync, v1.0.0
pigments, v0.24.2
sync-settings, v0.6.0
tabs-to-spaces, v1.0.2
translator-plus-dictionary, v0.1.0
travis-ci-status, v1.0.0
tree-view-finder, v0.2.1

# Dev
No dev packages
```

**Comment by HiroakiMikami** [comment]
I fixed this problem. Please try v0.2.0.

Thanks.

**Comment by WantedGaming** [comment]
where is version 0.2.0? I only see 1.1.1 version.

**Comment by HiroakiMikami** [comment]
Sorry, I wrote the version incorrectly. The correct version is `v0.2.0`, and the latest version (`v.1.1.1`) also fixed this error.
